version: "3.3"

services:
  app:
    build: .
    environment:
      MONGO_URL: "mongodb://db:27017/test"
    ports:
      - "3000:3000"
    volumes:
      - .:/usr/app/server
      - /usr/app/server/node_modules
    command: npx nodemon index.js